# 将来的には対応する規約の読込
inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込（RuboCopの機能拡張）
require:
  - rubocop-rails
  - rubocop-discourse
AllCops:
  # AllCopsオプションで全てのCopsを対象にできる
  NewCops: enable
  # 除外
  Exclude:
    - "config.ru"
    - "bin/**"
    - "lib/**"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - !ruby/regexp /old_and_unused\.rb$/
    - "vendor/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"

# Rails向けのRails copsを実行。"rubocop -R"と同じ
Rails:
  Enabled: true

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# rubocopが用意している独自のスコア（Assignment、Branch、Condition）の上限値を25点にする
Metrics/AbcSize:
  Max: 25

# 1つのメソッドの上限行数を25行までとする。
Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Enabled: false
